version: 2.1

executors:
  node:
    parameters:
      image:
        type: string
        default: "10"
    docker:
      - image: circleci/node:<< parameters.image >>

  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable

aliases:
  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: npm ci

  test_template: &test_template
    steps:
      - checkout
      - <<: *install_node_modules
      - run: npm test -- -w 1

jobs:
  lint:
    executor: node
    steps:
      - checkout
      - <<: *install_node_modules
      - run: npm run lint

  shellcheck:
    executor: shellcheck
    steps:
      - checkout
      - run: shellcheck --external-sources sketchtool.sh

  generate_mocks:
    executor: node
    steps:
      - checkout
      - <<: *install_node_modules
      - run:
          name: Generate Mocks
          command: |
            bash generate_mocks.sh
            test $(find __mocks__/figma/assets -type f -name "*.png" | wc -l | sed -e 's/^[ \t]*//') -eq 6
            test $(find __mocks__/figma/assets -type f -name "*.svg" | wc -l | sed -e 's/^[ \t]*//') -eq 3

  unit_tests_node_lts:
    executor: node
    <<: *test_template

  unit_tests_node_current:
    executor:
      name: node
      image: "12"
    <<: *test_template

  verify_readme:
    docker:
      - image: circleci/ruby
    steps:
      - run: gem install awesome_bot
      - checkout
      - run: awesome_bot README.md --allow-redirect --allow-dupe -w "https://github.com/inthepocket/hubble-app"

  build:
    executor: node
    steps:
      - checkout
      - <<: *install_node_modules
      - run:
          name: Build artifacts (binary + node runtime)
          command: npm run build
      - run:
          name: Verify version match
          command: |
            [ $(npx -c 'echo "$npm_package_version"') = $(./bin/hubble-cli-linux-x64 --version) ]
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish_github_release:
    docker:
      - image: cibuilds/github
    steps:
      - attach_workspace:
          at: .
      - run: apk add tree
      - run:
          name: Publish Github release
          command: |
            tree . -L 2
            VERSION="$(bin/hubble-cli-linux-x64 --version)"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} bin/

workflows:
  version: 2

  static_analysis:
    jobs:
      - lint
      - verify_readme

  test:
    jobs:
      - generate_mocks
      - unit_tests_node_lts:
          requires:
            - generate_mocks
      - unit_tests_node_current:
          requires:
            - generate_mocks
      - build:
          requires:
            - generate_mocks
            - unit_tests_node_lts

  publish_release:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish_github_release:
          requires:
            - build
